### ISSUE TITLE
louder speakers

### ISSUE THREAD

**Issue by vnabatov** [spaceshipyard/mars-rover-constructive#15]

**Comment by vicnbt** [comment]
probably we need another android 7 device, maybe tablet

**Comment by vicnbt** [comment]
I've got Jabra Drive for microphone and loud speaker

**Comment by vicnbt** [comment]
filed with all my devices
@chaos-adept maybe we could try to use raspberry 
```
phone[camera]===usb===> raspberry <===bluetooth===Jabra Drive[microphone, speaker]
                           /\
                           ||
                           ??
                           ||
                          pilot
```

**Comment by vnabatov** [comment]
will buy new android 7 phone after test in the shop

**Comment by vnabatov** [comment]
maybe better to use a tablet with androind 7

**Comment by vnabatov** [comment]
looks like this is it, so moving to closed
